---
title: "Untitled"
author: "R.W."
date: '2023-01-23'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# library
```{r}
library(ggplot2)
library(ggsignif)
library(ggbeeswarm)
library(ggpubr)
library(beeswarm)
library(vipor)
library(ggfortify)
library(VennDiagram)
library(RColorBrewer)
library(corrplot)
library(factoextra)
library(epitools)
library(gridExtra)
```

# read in all polished data
```{r}
all = read.csv("~/Documents/08PHTS_WGS_mt/variant/proband_remove/new_all.txt",sep="\t")
short_phenotype = read.csv("~/Documents/08PHTS_WGS_mt/variant/proband_remove/new_short_phenotypes_wCN.csv",sep="\t")
short_all = read.csv("~/Documents/08PHTS_WGS_mt/variant/proband_remove/new_short_all.csv",sep="\t")

onlyASD = short_all[which(short_all$phenotype=="ASD"),]
onlyCancer = short_all[which(short_all$phenotype=="Cancer"),]
ASDCancer = short_all[which(short_all$phenotype=="ASDCancer"),]
neither = short_all[which(short_all$phenotype=="neither"),]

for_CN=rbind.data.frame(onlyASD,onlyCancer,ASDCancer,neither)
for_CN$AGCNST = as.numeric(for_CN$AGCNST)

for_CN_H = for_CN[which(for_CN$haplogroup=="H"),]
table(for_CN_H$pheno)
```

# burden without insert
```{r}
all_no_insert = all[which(all$Mut.type=="transition"|all$Mut.type=="transversion"),]
 
temp = as.data.frame(table(all_no_insert$SAMPLEID))

temp$Var1 = as.character(temp$Var1)

temp = temp[order(temp$Var1),]
for_CN = for_CN[order(for_CN$LEGCUSTID),]
for_CN$burden_noinsert = temp$Freq
for_CN_H = for_CN[which(for_CN$haplogroup=="H"),]
```


## wilcox test
```{r}
t1 = wilcox.test(for_CN_H[which(for_CN_H$pheno=="ASD"),"burden_noinsert"],for_CN_H[which(for_CN_H$pheno=="Cancer"),"burden_noinsert"])$p.value
t2 = wilcox.test(for_CN_H[which(for_CN_H$pheno=="ASD"),"burden_noinsert"],for_CN_H[which(for_CN_H$pheno=="ASDCancer"),"burden_noinsert"])$p.value
t3 = wilcox.test(for_CN_H[which(for_CN_H$pheno=="ASDCancer"),"burden_noinsert"],for_CN_H[which(for_CN_H$pheno=="Cancer"),"burden_noinsert"])$p.value
t4 = wilcox.test(for_CN_H[which(for_CN_H$pheno=="ASD"),"burden_noinsert"],for_CN_H[which(for_CN_H$pheno=="neither"),"burden_noinsert"])$p.value
t5 = wilcox.test(for_CN_H[which(for_CN_H$pheno=="Cancer"),"burden_noinsert"],for_CN_H[which(for_CN_H$pheno=="neither"),"burden_noinsert"])$p.value
t6 = wilcox.test(for_CN_H[which(for_CN_H$pheno=="ASDCancer"),"burden_noinsert"],for_CN_H[which(for_CN_H$pheno=="neither"),"burden_noinsert"])$p.value
```

```{r}
burden_heat = rbind.data.frame(
c(t1,"onlyASD","onlyCancer"),
#c(t2,"onlyASD","ASDCancer"),
c(t3,"ASDCancer","onlyCancer"),
#c(t4,"onlyASD","neither"),
#c(t5,"onlyCancer","neither"),
c(t6,"ASDCancer","neither"),
#c(t1,"onlyCancer","onlyASD"),
c(t2,"ASDCancer","onlyASD"),
#c(t3,"onlyCancer","ASDCancer"),
c(t4,"neither","onlyASD"),
c(t5,"neither","onlyCancer"),
#c(t6,"neither","ASDCancer"),
c(1,"ASDCancer","ASDCancer"),
c(1,"onlyASD","onlyASD"),
c(1,"onlyCancer","onlyCancer"),
c(1,"neither","neither")
)

colnames(burden_heat) = c("p value","phenotype1","phenotype2")
burden_heat$`p value` = as.numeric(burden_heat$`p value`)
```

```{r}
temp = for_CN_H[which(for_CN_H$pheno=="Cancer"|for_CN_H$pheno=="ASD"),]
temp$pheno = as.factor(temp$pheno)
temp$AGCNST = as.numeric(temp$AGCNST)
temp$SEX = as.factor(temp$SEX)
summary(glm(pheno ~ burden + SEX + AGCNST,data=temp, family = "binomial"))
summary(glm(pheno ~ burden + SEX ,data=temp, family = "binomial"))
summary(glm(pheno ~ burden + AGCNST,data=temp, family = "binomial"))
summary(glm(pheno ~ burden ,data=temp, family = "binomial"))

dat_onlyasdonlycancer_burden_sex_age = glm(pheno ~ CN + SEX + AGCNST,data=temp,family = "binomial")
dat_onlyasdonlycancer_burden_age = glm(pheno ~ CN + AGCNST,data=temp,family = "binomial")
dat_onlyasdonlycancer_burden_sex = glm(pheno ~ CN + SEX,data=temp,family = "binomial")
dat_onlyasdonlycancer_burden = glm(pheno ~ CN,data=temp,family = "binomial")




temp = for_CN_H[which(for_CN_H$pheno=="ASDCancer"|for_CN_H$pheno=="ASD"),]
temp$pheno = as.factor(temp$pheno)
temp$AGCNST = as.numeric(temp$AGCNST)
temp$SEX = as.factor(temp$SEX)
summary(glm(pheno ~ burden + SEX + AGCNST,data=temp, family = "binomial"))
summary(glm(pheno ~ burden + SEX ,data=temp, family = "binomial"))
summary(glm(pheno ~ burden + AGCNST,data=temp, family = "binomial"))
summary(glm(pheno ~ burden ,data=temp, family = "binomial"))

dat_onlyasdasdcancer_burden_sex_age = glm(pheno ~ CN + SEX + AGCNST,data=temp,family = "binomial")
dat_onlyasdasdcancer_burden_age = glm(pheno ~ CN + AGCNST,data=temp,family = "binomial")
dat_onlyasdasdcancer_burden_sex = glm(pheno ~ CN + SEX,data=temp,family = "binomial")
dat_onlyasdasdcancer_burden = glm(pheno ~ CN,data=temp,family = "binomial")


temp = for_CN_H[which(for_CN_H$pheno=="neither"|for_CN_H$pheno=="ASD"),]
temp$pheno = as.factor(temp$pheno)
temp$AGCNST = as.numeric(temp$AGCNST)
temp$SEX = as.factor(temp$SEX)
summary(glm(pheno ~ burden + SEX + AGCNST,data=temp, family = "binomial"))
summary(glm(pheno ~ burden + SEX ,data=temp, family = "binomial"))
summary(glm(pheno ~ burden + AGCNST,data=temp, family = "binomial"))
summary(glm(pheno ~ burden ,data=temp, family = "binomial"))

dat_onlyasdneither_burden_sex_age = glm(pheno ~ CN + SEX + AGCNST,data=temp,family = "binomial")
dat_onlyasdneither_burden_age = glm(pheno ~ CN + AGCNST,data=temp,family = "binomial")
dat_onlyasdneither_burden_sex = glm(pheno ~ CN + SEX,data=temp,family = "binomial")
dat_onlyasdneither_burden = glm(pheno ~ CN,data=temp,family = "binomial")

temp = for_CN_H[which(for_CN_H$pheno=="Cancer"|for_CN_H$pheno=="ASDCancer"),]
temp$pheno = as.factor(temp$pheno)
temp$AGCNST = as.numeric(temp$AGCNST)
temp$SEX = as.factor(temp$SEX)
summary(glm(pheno ~ burden + SEX + AGCNST,data=temp, family = "binomial"))
summary(glm(pheno ~ burden + SEX ,data=temp, family = "binomial"))
summary(glm(pheno ~ burden + AGCNST,data=temp, family = "binomial"))
summary(glm(pheno ~ burden ,data=temp, family = "binomial"))

dat_onlycancerasdcancer_burden_sex_age = glm(pheno ~ CN + SEX + AGCNST,data=temp,family = "binomial")
dat_onlycancerasdcancer_burden_age = glm(pheno ~ CN + AGCNST,data=temp,family = "binomial")
dat_onlycancerasdcancer_burden_sex = glm(pheno ~ CN + SEX,data=temp,family = "binomial")
dat_onlycancerasdcancer_burden = glm(pheno ~ CN,data=temp,family = "binomial")


temp = for_CN_H[which(for_CN_H$pheno=="Cancer"|for_CN_H$pheno=="neither"),]
temp$pheno = as.factor(temp$pheno)
temp$AGCNST = as.numeric(temp$AGCNST)
temp$SEX = as.factor(temp$SEX)
summary(glm(pheno ~ burden + SEX + AGCNST,data=temp, family = "binomial"))
summary(glm(pheno ~ burden + SEX ,data=temp, family = "binomial"))
summary(glm(pheno ~ burden + AGCNST,data=temp, family = "binomial"))
summary(glm(pheno ~ burden ,data=temp, family = "binomial"))

dat_onlycancerneither_burden_sex_age = glm(pheno ~ CN + SEX + AGCNST,data=temp,family = "binomial")
dat_onlycancerneither_burden_age = glm(pheno ~ CN + AGCNST,data=temp,family = "binomial")
dat_onlycancerneither_burden_sex = glm(pheno ~ CN + SEX,data=temp,family = "binomial")
dat_onlycancerneither_burden = glm(pheno ~ CN,data=temp,family = "binomial")



temp = for_CN_H[which(for_CN_H$pheno=="ASDCancer"|for_CN_H$pheno=="neither"),]
temp$pheno = as.factor(temp$pheno)
temp$AGCNST = as.numeric(temp$AGCNST)
temp$SEX = as.factor(temp$SEX)
summary(glm(pheno ~ burden + SEX + AGCNST,data=temp, family = "binomial"))
summary(glm(pheno ~ burden + SEX ,data=temp, family = "binomial"))
summary(glm(pheno ~ burden + AGCNST,data=temp, family = "binomial"))
summary(glm(pheno ~ burden ,data=temp, family = "binomial"))

dat_asdcancerneither_burden_sex_age = glm(pheno ~ CN + SEX + AGCNST,data=temp,family = "binomial")
dat_asdcancerneither_burden_age = glm(pheno ~ CN + AGCNST,data=temp,family = "binomial")
dat_asdcancerneither_burden_sex = glm(pheno ~ CN + SEX,data=temp,family = "binomial")
dat_asdcancerneither_burden = glm(pheno ~ CN,data=temp,family = "binomial")
```

### forest plot
#### onlyasd onlycancer
```{r}
dat_onlyasdonlycancer = rbind.data.frame(exp(cbind(coef(dat_onlyasdonlycancer_burden), confint(dat_onlyasdonlycancer_burden)))[2,], 
exp(cbind(coef(dat_onlyasdonlycancer_burden_sex), confint(dat_onlyasdonlycancer_burden_sex)))[2,], exp(cbind(coef(dat_onlyasdonlycancer_burden_age), confint(dat_onlyasdonlycancer_burden_age)))[2,], exp(cbind(coef(dat_onlyasdonlycancer_burden_sex_age), confint(dat_onlyasdonlycancer_burden_sex_age)))[2,])  
colnames(dat_onlyasdonlycancer) = c("OR","2.5%","97.5%")
dat_onlyasdonlycancer$variants = c("only burden","burden and sex","burden and age","burden, sex and age")

ggplot(data=dat_onlyasdonlycancer, aes(y=variants, x=OR, xmin=`2.5%`, xmax=`97.5%`)) +
  geom_point(shape=15,size=3,color="blue") +
  geom_errorbarh(height=.1) +
  #scale_x_continuous(breaks=1:nrow(dat_cancer), labels=dat_cancer$variants) +
  labs(title='', x='Odds Ratio', y = 'variants included in variant\nburden logistic\nregression model') +
  geom_vline(xintercept=1, color='black', linetype='dashed', alpha=.5) +
  theme_classic() +
  theme(
  axis.title = element_text(size = 12),
  axis.text = element_text(size = 12)
)
```

#### onlyasd asdcancer
```{r}
dat_onlyasdasdcancer = rbind.data.frame(exp(cbind(coef(dat_onlyasdasdcancer_burden), confint(dat_onlyasdasdcancer_burden)))[2,], 
exp(cbind(coef(dat_onlyasdasdcancer_burden_sex), confint(dat_onlyasdasdcancer_burden_sex)))[2,], exp(cbind(coef(dat_onlyasdasdcancer_burden_age), confint(dat_onlyasdasdcancer_burden_age)))[2,], exp(cbind(coef(dat_onlyasdasdcancer_burden_sex_age), confint(dat_onlyasdasdcancer_burden_sex_age)))[2,])  
colnames(dat_onlyasdasdcancer) = c("OR","2.5%","97.5%")
dat_onlyasdasdcancer$variants = c("only burden","burden and sex","burden and age","burden, sex and age")

ggplot(data=dat_onlyasdasdcancer, aes(y=variants, x=OR, xmin=`2.5%`, xmax=`97.5%`)) +
  geom_point(shape=15,size=3,color="blue") +
  geom_errorbarh(height=.1) +
  #scale_x_continuous(breaks=1:nrow(dat_cancer), labels=dat_cancer$variants) +
  labs(title='', x='Odds Ratio', y = 'variants included in variant\nburden logistic\nregression model') +
  geom_vline(xintercept=1, color='black', linetype='dashed', alpha=.5) +
  theme_classic() +
  theme(
  axis.title = element_text(size = 12),
  axis.text = element_text(size = 12)
)
ggsave("~/Documents/08PHTS_WGS_mt/manuscript/20230119HGGAdvancessubmissionRW/#2response/230314_burden_onlyasdasdcancer_forestplot.pdf",width = 6, height = 4)
```
#### onlyasdneither
```{r}
dat_onlyasdneither = rbind.data.frame(exp(cbind(coef(dat_onlyasdneither_burden), confint(dat_onlyasdneither_burden)))[2,], 
exp(cbind(coef(dat_onlyasdneither_burden_sex), confint(dat_onlyasdneither_burden_sex)))[2,], exp(cbind(coef(dat_onlyasdneither_burden_age), confint(dat_onlyasdneither_burden_age)))[2,], exp(cbind(coef(dat_onlyasdneither_burden_sex_age), confint(dat_onlyasdneither_burden_sex_age)))[2,])  
colnames(dat_onlyasdneither) = c("OR","2.5%","97.5%")
dat_onlyasdneither$variants = c("only burden","burden and sex","burden and age","burden, sex and age")

ggplot(data=dat_onlyasdneither, aes(y=variants, x=OR, xmin=`2.5%`, xmax=`97.5%`)) +
  geom_point(shape=15,size=3,color="blue") +
  geom_errorbarh(height=.1) +
  #scale_x_continuous(breaks=1:nrow(dat_cancer), labels=dat_cancer$variants) +
  labs(title='', x='Odds Ratio', y = 'variants included in variant\nburden logistic\nregression model') +
  geom_vline(xintercept=1, color='black', linetype='dashed', alpha=.5) +
  theme_classic() +
  theme(
  axis.title = element_text(size = 12),
  axis.text = element_text(size = 12)
)
ggsave("~/Documents/08PHTS_WGS_mt/manuscript/20230119HGGAdvancessubmissionRW/#2response/230314_burden_onlyasdneither_forestplot.pdf",width = 6, height = 4)
```

#### onlycancer neither
```{r}
dat_onlycancerneither = rbind.data.frame(exp(cbind(coef(dat_onlycancerneither_burden), confint(dat_onlycancerneither_burden)))[2,], 
exp(cbind(coef(dat_onlycancerneither_burden_sex), confint(dat_onlycancerneither_burden_sex)))[2,], exp(cbind(coef(dat_onlycancerneither_burden_age), confint(dat_onlycancerneither_burden_age)))[2,], exp(cbind(coef(dat_onlycancerneither_burden_sex_age), confint(dat_onlycancerneither_burden_sex_age)))[2,])  
colnames(dat_onlycancerneither) = c("OR","2.5%","97.5%")
dat_onlycancerneither$variants = c("only burden","burden and sex","burden and age","burden, sex and age")

ggplot(data=dat_onlycancerneither, aes(y=variants, x=OR, xmin=`2.5%`, xmax=`97.5%`)) +
  geom_point(shape=15,size=3,color="blue") +
  geom_errorbarh(height=.1) +
  #scale_x_continuous(breaks=1:nrow(dat_cancer), labels=dat_cancer$variants) +
  labs(title='', x='Odds Ratio', y = 'variants included in variant\nburden logistic\nregression model') +
  geom_vline(xintercept=1, color='black', linetype='dashed', alpha=.5) +
  theme_classic() +
  theme(
  axis.title = element_text(size = 12),
  axis.text = element_text(size = 12)
)
ggsave("~/Documents/08PHTS_WGS_mt/manuscript/20230119HGGAdvancessubmissionRW/#2response/230314_burden_onlycancerneither_forestplot.pdf",width = 6, height = 4)
```

#### onlycancer asdcancer
```{r}
dat_onlycancerasdcancer = rbind.data.frame(exp(cbind(coef(dat_onlycancerasdcancer_burden), confint(dat_onlycancerasdcancer_burden)))[2,], 
exp(cbind(coef(dat_onlycancerasdcancer_burden_sex), confint(dat_onlycancerasdcancer_burden_sex)))[2,], exp(cbind(coef(dat_onlycancerasdcancer_burden_age), confint(dat_onlycancerasdcancer_burden_age)))[2,], exp(cbind(coef(dat_onlycancerasdcancer_burden_sex_age), confint(dat_onlycancerasdcancer_burden_sex_age)))[2,])  
colnames(dat_onlycancerasdcancer) = c("OR","2.5%","97.5%")
dat_onlycancerasdcancer$variants = c("only burden","burden and sex","burden and age","burden, sex and age")

ggplot(data=dat_onlycancerasdcancer, aes(y=variants, x=OR, xmin=`2.5%`, xmax=`97.5%`)) +
  geom_point(shape=15,size=3,color="blue") +
  geom_errorbarh(height=.1) +
  #scale_x_continuous(breaks=1:nrow(dat_cancer), labels=dat_cancer$variants) +
  labs(title='', x='Odds Ratio', y = 'variants included in variant\nburden logistic\nregression model') +
  geom_vline(xintercept=1, color='black', linetype='dashed', alpha=.5) +
  theme_classic() +
  theme(
  axis.title = element_text(size = 12),
  axis.text = element_text(size = 12)
)
ggsave("~/Documents/08PHTS_WGS_mt/manuscript/20230119HGGAdvancessubmissionRW/#2response/230314_burden_onlycancerasdcancer_forestplot.pdf",width = 6, height = 4)
```


#### asdcancer neither
```{r}
dat_asdcancerneither = rbind.data.frame(exp(cbind(coef(dat_asdcancerneither_burden), confint(dat_asdcancerneither_burden)))[2,], 
exp(cbind(coef(dat_asdcancerneither_burden_sex), confint(dat_asdcancerneither_burden_sex)))[2,], exp(cbind(coef(dat_asdcancerneither_burden_age), confint(dat_asdcancerneither_burden_age)))[2,], exp(cbind(coef(dat_asdcancerneither_burden_sex_age), confint(dat_asdcancerneither_burden_sex_age)))[2,])  
colnames(dat_asdcancerneither) = c("OR","2.5%","97.5%")
dat_asdcancerneither$variants = c("only burden","burden and sex","burden and age","burden, sex and age")

ggplot(data=dat_asdcancerneither, aes(y=variants, x=OR, xmin=`2.5%`, xmax=`97.5%`)) +
  geom_point(shape=15,size=3,color="blue") +
  geom_errorbarh(height=.1) +
  #scale_x_continuous(breaks=1:nrow(dat_cancer), labels=dat_cancer$variants) +
  labs(title='', x='Odds Ratio', y = 'variants included in variant\nburden logistic\nregression model') +
  geom_vline(xintercept=1, color='black', linetype='dashed', alpha=.5) +
  theme_classic() +
  theme(
  axis.title = element_text(size = 12),
  axis.text = element_text(size = 12)
)
```


## asd vs. no asd
```{r}
for_CN_H$asd_phenotype = "ASD"
for_CN_H[which(for_CN_H$pheno=="Cancer"|for_CN_H$pheno=="neither"),"asd_phenotype"] = "noASD"
```

```{r}
for_CN_H$asd_phenotype = as.character(for_CN_H$asd_phenotype)
temp = for_CN_H
temp$asd_phenotype = as.factor(temp$asd_phenotype)
temp$SEX = as.factor(temp$SEX)
temp$AGCNST = as.numeric(temp$AGCNST)
temp$asd_phenotype = as.factor(temp$asd_phenotype)
summary(glm(asd_phenotype ~ burden_noinsert + SEX + AGCNST,data=temp,family = "binomial"))
summary(glm(asd_phenotype ~ burden_noinsert + SEX ,data=temp,family = "binomial"))
summary(glm(asd_phenotype ~ burden_noinsert + AGCNST,data=temp,family = "binomial"))
summary(glm(asd_phenotype ~ burden_noinsert,data=temp,family = "binomial"))

dat_asd_burden_sex_age = glm(asd_phenotype ~ burden_noinsert + SEX + AGCNST,data=temp,family = "binomial")

dat_asd_burden_age = glm(asd_phenotype ~ burden_noinsert+ AGCNST,data=temp,family = "binomial")

dat_asd_burden_sex = glm(asd_phenotype ~ burden_noinsert + SEX,data=temp,family = "binomial")

dat_asd_burden = glm(asd_phenotype ~ burden_noinsert,data=temp,family = "binomial")


wilcox.test(temp[which(temp$asd_phenotype=="ASD"),"burden_noinsert"],temp[which(temp$asd_phenotype=="noASD"),"burden_noinsert"])
```

```{r}
dat_asd = rbind.data.frame(exp(cbind(coef(dat_asd_burden), confint(dat_asd_burden)))[2,], 
exp(cbind(coef(dat_asd_burden_sex), confint(dat_asd_burden_sex)))[2,], exp(cbind(coef(dat_asd_burden_age), confint(dat_asd_burden_age)))[2,], exp(cbind(coef(dat_asd_burden_sex_age), confint(dat_asd_burden_sex_age)))[2,])  
colnames(dat_asd) = c("OR","2.5%","97.5%")
dat_asd$variants = c("only burden","burden and sex","burden and age","burden, sex and age")

ggplot(data=dat_asd, aes(y=variants, x=OR, xmin=`2.5%`, xmax=`97.5%`)) +
  geom_point(shape=15,size=3,color="blue") +
  geom_errorbarh(height=.1) +
  #scale_x_continuous(breaks=1:nrow(dat_cancer), labels=dat_cancer$variants) +
  labs(title='', x='Odds Ratio', y = 'variants included in variant\nburden logistic\nregression model') +
  geom_vline(xintercept=1, color='black', linetype='dashed', alpha=.5) +
  theme_classic() +
  theme(
  axis.title = element_text(size = 12),
  axis.text = element_text(size = 12)
)
```

## asd vs. neither
```{r}
temp = for_CN_H[which(for_CN_H$asd_phenotype=="ASD"),]
temp$asdneither_pheno = "ASD"
temp1 = for_CN_H[which(for_CN_H$pheno=="neither"),]
temp1$asdneither_pheno = "neither"
temp = rbind.data.frame(temp,temp1)

wilcox.test(temp[which(temp$asdneither_pheno=="ASD"),"burden_noinsert"],temp[which(temp$asdneither_pheno=="neither"),"burden_noinsert"])

temp$SEX = as.factor(temp$SEX)
temp$asdneither_pheno = as.factor(temp$asdneither_pheno)
temp$AGCNST = as.numeric(temp$AGCNST)
temp$SEX = as.factor(temp$SEX)

summary(glm(asdneither_pheno ~ burden_noinsert + SEX + AGCNST,data=temp,family = "binomial"))
summary(glm(asdneither_pheno ~ burden_noinsert + SEX ,data=temp,family = "binomial"))
summary(glm(asdneither_pheno ~ burden_noinsert + AGCNST,data=temp,family = "binomial"))
summary(glm(asdneither_pheno ~ burden_noinsert ,data=temp,family = "binomial"))

dat_asdneither_burden_sex_age = glm(asdneither_pheno ~ burden_noinsert + SEX + AGCNST,data=temp,family = "binomial")

dat_asdneither_burden_age = glm(asdneither_pheno ~ burden_noinsert + AGCNST,data=temp,family = "binomial")

dat_asdneither_burden_sex = glm(asdneither_pheno ~ burden_noinsert + SEX,data=temp,family = "binomial")

dat_asdneither_burden = glm(asdneither_pheno ~ burden_noinsert,data=temp,family = "binomial")
```

```{r}
dat_asdneither = rbind.data.frame(exp(cbind(coef(dat_asdneither_burden), confint(dat_asdneither_burden)))[2,], 
exp(cbind(coef(dat_asdneither_burden_sex), confint(dat_asdneither_burden_sex)))[2,], exp(cbind(coef(dat_asdneither_burden_age), confint(dat_asdneither_burden_age)))[2,], exp(cbind(coef(dat_asdneither_burden_sex_age), confint(dat_asdneither_burden_sex_age)))[2,])  
colnames(dat_asdneither) = c("OR","2.5%","97.5%")
dat_asdneither$variants = c("only burden","burden and sex","burden and age","burden, sex and age")

ggplot(data=dat_asdneither, aes(y=variants, x=OR, xmin=`2.5%`, xmax=`97.5%`)) +
  geom_point(shape=15,size=3,color="blue") +
  geom_errorbarh(height=.1) +
  #scale_x_continuous(breaks=1:nrow(dat_cancer), labels=dat_cancer$variants) +
  labs(title='', x='Odds Ratio', y = 'variants included in variant\nburden logistic\nregression model') +
  geom_vline(xintercept=1, color='black', linetype='dashed', alpha=.5) +
  theme_classic() +
  theme(
  axis.title = element_text(size = 12),
  axis.text = element_text(size = 12)
)
```

## cancer vs. no cancer
```{r}
for_CN_H$cancer_phenotype = "Cancer"
for_CN_H[which(for_CN_H$pheno=="ASD"|for_CN_H$pheno=="neither"),"cancer_phenotype"] = "noCancer"

wilcox.test(for_CN_H[which(for_CN_H$cancer_phenotype=="Cancer"),"burden_noinsert"],for_CN_H[which(for_CN_H$cancer_phenotype=="noCancer"),"burden_noinsert"])

temp = for_CN_H
temp$cancer_phenotype = as.factor(temp$cancer_phenotype)
temp = for_CN_H
temp$cancer_phenotype = as.factor(temp$cancer_phenotype)
temp$SEX = as.numeric(as.factor(temp$SEX))

summary(glm(cancer_phenotype ~ burden_noinsert + SEX + AGCNST,data=temp,family = "binomial"))
summary(glm(cancer_phenotype ~ burden_noinsert + SEX ,data=temp,family = "binomial"))
summary(glm(cancer_phenotype ~ burden_noinsert + AGCNST,data=temp,family = "binomial"))
summary(glm(cancer_phenotype ~ burden_noinsert ,data=temp,family = "binomial"))


dat_cancernocancer_burden_sex_age = glm(cancer_phenotype ~ burden_noinsert + SEX + AGCNST,data=temp,family = "binomial")
dat_cancernocancer_burden_age = glm(cancer_phenotype ~ burden_noinsert + AGCNST,data=temp,family = "binomial")
dat_cancernocancer_burden_sex = glm(cancer_phenotype ~ burden_noinsert + SEX,data=temp,family = "binomial")
dat_cancernocancer_burden = glm(cancer_phenotype ~ burden_noinsert,data=temp,family = "binomial")
```

```{r}
dat_cancernocancer = rbind.data.frame(exp(cbind(coef(dat_cancernocancer_burden), confint(dat_cancernocancer_burden)))[2,], 
exp(cbind(coef(dat_cancernocancer_burden_sex), confint(dat_cancernocancer_burden_sex)))[2,], exp(cbind(coef(dat_cancernocancer_burden_age), confint(dat_cancernocancer_burden_age)))[2,], exp(cbind(coef(dat_cancernocancer_burden_sex_age), confint(dat_cancernocancer_burden_sex_age)))[2,])  
colnames(dat_cancernocancer) = c("OR","2.5%","97.5%")
dat_cancernocancer$variants = c("only burden","burden and sex","burden and age","burden, sex and age")

ggplot(data=dat_cancernocancer, aes(y=variants, x=OR, xmin=`2.5%`, xmax=`97.5%`)) +
  geom_point(shape=15,size=3,color="blue") +
  geom_errorbarh(height=.1) +
  #scale_x_continuous(breaks=1:nrow(dat_cancer), labels=dat_cancer$variants) +
  labs(title='', x='Odds Ratio', y = 'variants included in variant\nburden logistic\nregression model') +
  geom_vline(xintercept=1, color='black', linetype='dashed', alpha=.5) +
  theme_classic() +
  theme(
  axis.title = element_text(size = 12),
  axis.text = element_text(size = 12)
)
```

## cancer vs. neither
```{r}
temp = for_CN_H[which(for_CN_H$cancer_phenotype=="Cancer"),]
temp$cancerneither_pheno = "Cancer"
temp1 = for_CN_H[which(for_CN_H$pheno=="neither"),]
temp1$cancerneither_pheno = "neither"
temp = rbind.data.frame(temp,temp1)

wilcox.test(temp[which(temp$pheno=="Cancer"),"burden_noinsert"],temp[which(temp$pheno=="neither"),"burden_noinsert"])

temp$cancerneither_pheno = as.factor(temp$cancerneither_pheno)
temp$SEX = as.factor(temp$SEX)
temp$AGCNST = as.numeric(temp$AGCNST)

summary(glm(cancerneither_pheno ~ burden_noinsert + SEX + AGCNST,data=temp,family = "binomial"))
summary(glm(cancerneither_pheno ~ burden_noinsert + SEX ,data=temp,family = "binomial"))
summary(glm(cancerneither_pheno ~ burden_noinsert + AGCNST,data=temp,family = "binomial"))
summary(glm(cancerneither_pheno ~ burden_noinsert ,data=temp,family = "binomial"))


dat_cancer_burden_sex_age = glm(cancerneither_pheno ~ burden_noinsert + SEX + AGCNST,data=temp,family = "binomial")

dat_cancer_burden_age = glm(cancerneither_pheno ~ burden_noinsert + AGCNST,data=temp,family = "binomial")

dat_cancer_burden_sex = glm(cancerneither_pheno ~ burden_noinsert + SEX,data=temp,family = "binomial")

dat_cancer_burden = glm(cancerneither_pheno ~ burden_noinsert,data=temp,family = "binomial")
```

```{r}
dat_cancer = rbind.data.frame(exp(cbind(coef(dat_cancer_burden), confint(dat_cancer_burden)))[2,], 
exp(cbind(coef(dat_cancer_burden_sex), confint(dat_cancer_burden_sex)))[2,], exp(cbind(coef(dat_cancer_burden_age), confint(dat_cancer_burden_age)))[2,], exp(cbind(coef(dat_cancer_burden_sex_age), confint(dat_cancer_burden_sex_age)))[2,])  
colnames(dat_cancer) = c("OR","2.5%","97.5%")
dat_cancer$variants = c("only burden","burden and sex","burden and age","burden, sex and age")

ggplot(data=dat_cancer, aes(y=variants, x=OR, xmin=`2.5%`, xmax=`97.5%`)) +
  geom_point(shape=15,size=3,color="blue") +
  geom_errorbarh(height=.1) +
  #scale_x_continuous(breaks=1:nrow(dat_cancer), labels=dat_cancer$variants) +
  labs(title='', x='Odds Ratio', y = 'variants included in variant\nburden logistic\nregression model') +
  geom_vline(xintercept=1, color='black', linetype='dashed', alpha=.5) +
  theme_classic() +
  theme(
  axis.title = element_text(size = 12),
  axis.text = element_text(size = 12)
)
```


## beswarrm plot of MW test resutls 
```{r}
temp = for_CN_H[which(for_CN_H$phenotype=="ASD" |for_CN_H$phenotype=="Cancer"),]
p_onlyasd_onlycancer = 
  ggplot(data=temp,aes(x=phenotype,y=burden_noinsert)) +
  geom_boxplot(fill=c("aquamarine","pink"),alpha=0.8) +
  geom_quasirandom(dodge.width=0.9,alpha=.4) +
  theme_bw() +
  #scale_fill_brewer(palette="YlOrRd",direction = 1) +
  ylab("Variant burden") +
  xlab("") +
  ylim(0,20) + 
  theme(axis.text.x=element_text(size=13,angle=0,hjust=0.5),
        axis.text.y=element_text(size=13),
        axis.title.x=element_text(size=15),
        axis.title.y=element_text(size=15),
        #legend.text= element_text(size=13),
        #legend.title = element_text(""),
        legend.position = "none",
        title = element_text(size=20))
```

```{r}
temp = for_CN_H[which(for_CN_H$phenotype=="ASD" |for_CN_H$phenotype=="ASDCancer"),]
p_onlyasd_asdcancer = 
  ggplot(data=temp,aes(x=phenotype,y=burden_noinsert)) +
  geom_boxplot(fill=c("pink","darkslateblue"),alpha=0.8) +
  geom_quasirandom(dodge.width=0.9,alpha=.4) +
  theme_bw() +
  #scale_fill_brewer(palette="YlOrRd",direction = 1) +
  ylab("Variant burden") +
  xlab("") +
  ylim(0,20) + 
  theme(axis.text.x=element_text(size=13,angle=0,hjust=0.5),
        axis.text.y=element_text(size=13),
        axis.title.x=element_text(size=15),
        axis.title.y=element_text(size=15),
        #legend.text= element_text(size=13),
        #legend.title = element_text(""),
        legend.position = "none",
        title = element_text(size=20))
```

```{r}
temp = for_CN_H[which(for_CN_H$phenotype=="ASD" |for_CN_H$phenotype=="neither"),]
temp$phenotype = factor(temp$phenotype,levels = c("ASD","neither"))
p_onlyasd_neither = 
  ggplot(data=temp,aes(x=phenotype,y=burden_noinsert)) +
  geom_boxplot(fill=c("pink","lightblue"),alpha=0.8) +
  geom_quasirandom(dodge.width=0.9,alpha=.4) +
  theme_bw() +
  #scale_fill_brewer(palette="YlOrRd",direction = 1) +
  ylab("Variant burden") +
  xlab("") +
  ylim(0,20) + 
  theme(axis.text.x=element_text(size=13,angle=0,hjust=0.5),
        axis.text.y=element_text(size=13),
        axis.title.x=element_text(size=15),
        axis.title.y=element_text(size=15),
        #legend.text= element_text(size=13),
        #legend.title = element_text(""),
        legend.position = "none",
        title = element_text(size=20))
```

```{r}
temp = for_CN_H[which(for_CN_H$phenotype=="Cancer" |for_CN_H$phenotype=="ASDCancer"),]
p_onlycancer_asdcancer = 
  ggplot(data=temp,aes(x=phenotype,y=burden_noinsert)) +
  geom_boxplot(fill=c("aquamarine","darkslateblue"),alpha=0.8) +
  geom_quasirandom(dodge.width=0.9,alpha=.4) +
  theme_bw() +
  #scale_fill_brewer(palette="YlOrRd",direction = 1) +
  ylab("Variant burden") +
  xlab("") +
  ylim(0,20) + 
  theme(axis.text.x=element_text(size=13,angle=0,hjust=0.5),
        axis.text.y=element_text(size=13),
        axis.title.x=element_text(size=15),
        axis.title.y=element_text(size=15),
        #legend.text= element_text(size=13),
        #legend.title = element_text(""),
        legend.position = "none",
        title = element_text(size=20))
```

```{r}
temp = for_CN_H[which(for_CN_H$phenotype=="Cancer" |for_CN_H$phenotype=="neither"),]
temp$phenotype = factor(temp$phenotype,levels = c("Cancer","neither"))
p_onlycancer_neitehr = 
  ggplot(data=temp,aes(x=phenotype,y=burden_noinsert)) +
  geom_boxplot(fill=c("aquamarine","lightblue"),alpha=0.8) +
  geom_quasirandom(dodge.width=0.9,alpha=.4) +
  theme_bw() +
  #scale_fill_brewer(palette="YlOrRd",direction = 1) +
  ylab("Variant burden") +
  xlab("") +
  ylim(0,20) + 
  theme(axis.text.x=element_text(size=13,angle=0,hjust=0.5),
        axis.text.y=element_text(size=13),
        axis.title.x=element_text(size=15),
        axis.title.y=element_text(size=15),
        #legend.text= element_text(size=13),
        #legend.title = element_text(""),
        legend.position = "none",
        title = element_text(size=20))
```

```{r}
temp = for_CN_H[which(for_CN_H$phenotype=="ASDCancer" |for_CN_H$phenotype=="neither"),]
temp$phenotype = factor(temp$phenotype,levels = c("ASDCancer","neither"))
p_neither_asdcancer = 
  ggplot(data=temp,aes(x=phenotype,y=burden_noinsert)) +
  geom_boxplot(fill=c("darkslateblue","lightblue"),alpha=0.8) +
  geom_quasirandom(dodge.width=0.9,alpha=.4) +
  theme_bw() +
  #scale_fill_brewer(palette="YlOrRd",direction = 1) +
  ylab("Variant burden") +
  xlab("") +
  ylim(0,20) + 
  theme(axis.text.x=element_text(size=13,angle=0,hjust=0.5),
        axis.text.y=element_text(size=13),
        axis.title.x=element_text(size=15),
        axis.title.y=element_text(size=15),
        #legend.text= element_text(size=13),
        #legend.title = element_text(""),
        legend.position = "none",
        title = element_text(size=20))
```

```{r}
p_asd = ggplot(data=for_CN_H,aes(x=asd_phenotype,y=burden)) +
  geom_boxplot(fill=c("lightcoral","gold"),alpha=0.8) +
  geom_quasirandom(dodge.width=0.9,alpha=.4) +
  theme_bw() +
  #scale_fill_brewer(palette="YlOrRd",direction = 1) +
  ylab("Variant burden") +
  xlab("") +
  ylim(0,20) + 
  theme(axis.text.x=element_text(size=13,angle=0,hjust=0.5),
        axis.text.y=element_text(size=13),
        axis.title.x=element_text(size=15),
        axis.title.y=element_text(size=15),
        #legend.text= element_text(size=13),
        #legend.title = element_text(""),
        legend.position = "none",
        title = element_text(size=20))
```

```{r}
p_cancer = ggplot(data=for_CN_H,aes(x=cancer_phenotype,y=burden,fill=cancer_phenotype)) +
  geom_boxplot(fill=c("darkgreen","greenyellow"),alpha=0.8) +
  geom_quasirandom(dodge.width=0.9,alpha=.4) +
  theme_bw() +
  scale_fill_brewer(palette="PuBu",direction = 1) +
  ylab("Variant burden") +
  xlab("") +
  ylim(0,20) + 
  theme(axis.text.x=element_text(size=13,angle=0,hjust=0.5),
        axis.text.y=element_text(size=13),
        axis.title.x=element_text(size=15),
        axis.title.y=element_text(size=15),
        #legend.text= element_text(size=13),
        #legend.title = element_text(""),
        legend.position = "none",
        title = element_text(size=20))
```


```{r}
temp1 = for_CN_H[which(for_CN_H$pheno=="ASD"|for_CN_H$pheno=="CancerASD"),]
temp1$pheno = "ASD"
temp2 = for_CN_H[which(for_CN_H$phenotype=="neither"),]
temp = rbind.data.frame(temp1,temp2)
p_asdneither = ggplot(data=temp,aes(x=pheno,y=burden_noinsert,fill=pheno)) +
  geom_boxplot(fill=c("lightcoral","lightblue"),alpha=0.8) +
  geom_quasirandom(dodge.width=0.9,alpha=.4) +
  theme_bw() +
  scale_fill_brewer(palette="PuBu",direction = 1) +
  ylab("Variant burden") +
  xlab("") +
  ylim(0,20) + 
  theme(axis.text.x=element_text(size=13,angle=0,hjust=0.5),
        axis.text.y=element_text(size=13),
        axis.title.x=element_text(size=15),
        axis.title.y=element_text(size=15),
        #legend.text= element_text(size=13),
        #legend.title = element_text(""),
        legend.position = "none",
        title = element_text(size=20))
```

```{r}
temp1 = for_CN_H[which(for_CN_H$pheno=="Cancer"|for_CN_H$pheno=="CancerASD"),]
temp1$pheno = "Cancer"
temp2 = for_CN_H[which(for_CN_H$phenotype=="neither"),]
temp = rbind.data.frame(temp1,temp2)
p_cancerneither = ggplot(data=temp,aes(x=pheno,y=burden_noinsert,fill=pheno)) +
  geom_boxplot(fill=c("darkgreen","lightblue"),alpha=0.8) +
  geom_quasirandom(dodge.width=0.9,alpha=.4) +
  theme_bw() +
  scale_fill_brewer(palette="PuBu",direction = 1) +
  ylab("Variant burden") +
  xlab("") +
  ylim(0,20) + 
  theme(axis.text.x=element_text(size=13,angle=0,hjust=0.5),
        axis.text.y=element_text(size=13),
        axis.title.x=element_text(size=15),
        axis.title.y=element_text(size=15),
        #legend.text= element_text(size=13),
        #legend.title = element_text(""),
        legend.position = "none",
        title = element_text(size=20))
```

```{r}
p = arrangeGrob(p_onlyasd_onlycancer,p_onlyasd_asdcancer,p_onlyasd_neither,p_onlycancer_neitehr,p_onlycancer_asdcancer,p_neither_asdcancer,p_asd, p_cancer, p_asdneither,p_cancerneither,nrow=5)
```


